defaults: &defaults
  adapter: sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000

sqlite: &sqlite
  <<: *defaults
  database: db/<%= Dbname.env[:test] %>.sqlite3

postgresql: &postgresql
  <<: *defaults
  adapter: postgresql
  encoding: unicode
  database: rgyazo_test
  host: localhost
  username: postgres
  password:

development:
  <<: *defaults
  database: db/<%= Dbname.env[:development] %>.sqlite3

test:
  <<: *<%= ENV['DB'] || "sqlite" %>

production:
  adapter: postgresql
  encoding: unicode
  database: r_gyazo_production
  pool: 5
  username: r_gyazo
  password:
