sqlite: &sqlite
  adapter: sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000
  database: db/<%= Dbname.env[:test] %>.sqlite3

postgresql: &postgresql
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: <%= Dbname.env[:test] %>
  host: localhost
  username: postgres
  password:

development:
  <<: *sqlite
  database: db/<%= Dbname.env[:development] %>.sqlite3

test:
  <<: *<%= ENV['DB'] || "sqlite" %>

production:
  adapter: postgresql
  encoding: unicode
  database: r_gyazo_production
  pool: 5
  username: r_gyazo
  password:
