defaults: &defaults
  adapter: sqlite3
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *defaults
  database: db/<%= Dbname.env[:development] %>.sqlite3

test:
  <<: *defaults
  database: db/<%= Dbname.env[:test] %>.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: r_gyazo_production
  pool: 5
  username: r_gyazo
  password:
